# Generated by Django 3.2.8 on 2021-10-18 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211018_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='address_info',
        ),
    ]
